### PR TITLE
Update pet name when changing launch template id

### PR DESCRIPTION
**Pull request by woz5999**
## what
* Update pet name when changing launch template id

## why
* If you change the template id, tf/aws will try to create a new node group; however, because we're using create before destroy, it errors out due to "NodeGroup already exists with name food and cluster name bar"
* generating a new pet name will restore the correct behavior
* note that this was the behavior prior to Overhaul #84

### CODE REVIEW

**Comment by woz5999** [comment]
@aknysh i ended up just creating a new fork since mine was so old. here's the fixed version of !105

**Comment by woz5999** [comment]
anyone available to review this?

**Comment by woz5999** [comment]
@aknysh @Nuru @Gowiem is anyone able to review this?

**Comment by Gowiem** [comment]
Since @Nuru did #84, I'll leave it to him.

**Pull request closed without merging**
