### PR TITLE
feat: migrates example on eks-cluster-aws-4.x

### PR DESCRIPTION
**Pull request by gberenice**
## what

- Upgrade the example to use eks-cluster v4.x.x, where any dependencies on the Kubernetes provider were removed.

## why

- This eliminates the Terraform test error caused by [the kubernetes provider issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2388). As a consequence, this unlocks merging the PRs. Example of the error:
```
Error: Received unexpected error:
FatalError{Underlying: error while running command: exit status 1; ╷
     │ Error: Value Conversion Error
     │ 
     │ with module.eks_cluster.provider["registry.terraform.io/hashicorp/kubernetes"],
     │ on .terraform/modules/eks_cluster/auth.tf line 96, in provider "kubernetes":
     │ 96: provider "kubernetes" {
```

## references

- [Migration guide](https://github.com/cloudposse/terraform-aws-eks-cluster/blob/4.0.0/docs/migration-v3-v4.md)
- [Latest example for eks-cluster](https://github.com/cloudposse/terraform-aws-eks-cluster/tree/4.0.0/examples/complete)
- [Initial discussion in the `contributors` Slack channel](https://sweetops.slack.com/archives/G014YEKDH4K/p1709911639196219)

### CODE REVIEW

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
Seems OK, as it's based on the referenced [PR](https://github.com/cloudposse/terraform-aws-eks-cluster/pull/206/files)

**Comment by Nuru** [comment]
@joe-niland @gberenice Thank you for this PR.

For future reference:

1. Any PRs that do not change the code of the Terraform module itself should be labeled `no-release` to avoid triggering the release of a new module version upon merging the PR. Without this label, a new release is created and people and systems feel the need to update to the new release, but the new release is exactly the same code, and it is just a waste of time and resources to upgrade. There are filters in place to try to catch PRs like this one that do not change any code and therefore do not trigger a release, and this PR was caught by the filter, but still, it is best practice to label the PR `no-release` to be on the safe side.
   
   Side note: you can also use `no-release` when you plan to merge several PRs in one day, so that you can bunch the changes and reduce the upgrade noise. 

3. PRs that do change the code, but only make small changes, should get `patch` or `bugfix` labels. I mention it because although this PR should have had the `no-release` label, failing that, it should have had the `patch` label.

4. Also, please note that any change to the Kubernetes version in the example requires a corresponding change to the Kubernetes Go packages in `test/src/go.mod` when such packages are present: https://github.com/cloudposse/terraform-aws-eks-node-group/blob/fa3d05a8cdb771ea1376775334ca67252970ea70/test/src/go.mod#L9-L10

   And then, of course, changing the `go.mod` file requires updating the `go.sum` file with `go mod tidy`.


See #177 for example.

https://github.com/cloudposse/terraform-aws-eks-node-group/blob/59e4145da6c28e05f4fe6b47f75af1b02257b728/test/src/go.mod#L11-L12

**Comment by gberenice** [comment]
Thanks for the explanation @Nuru. I feel like these important details should be described in the [community docs](https://docs.cloudposse.com/category/community/), but I can't find this info there. Am I missing something?

**Comment by Nuru** [comment]
> Thanks for the explanation @Nuru. I feel like these important details should be described in the [community docs](https://docs.cloudposse.com/category/community/), but I can't find this info there. Am I missing something?

@gberenice You are right, they should be, but are not, documented there. I made a note to update the [Code Review Guidelines](https://docs.cloudposse.com/community/code-reviews/).

**Comment by joe-niland** [comment]
@Nuru thanks for the notes. They are very helpful.

Agreed that it will be beneficial to document them.

It might also be helpful to update [CONTRIBUTING](https://github.com/cloudposse/.github/blob/main/CONTRIBUTING.md) because it covers labelling and updating of the examples.

**Pull request merged**
