### PR TITLE
Allow using multiple lines of before and after userdata

### LINKED ISSUE #123: after_cluster_joining_userdata only allows one element
## Describe the Bug
The validation of the variable `after_cluster_joining_userdata` expects the length of the array to be smaller than 2, but the definition says that it can contain commands in plural.

```
variable "after_cluster_joining_userdata" {
  type        = list(string)
  default     = []
  description = "Additional `bash` commands to execute on each worker node after joining the EKS cluster (after executing the `bootstrap.sh` script). For more info, see https://kubedex.com/90-days-of-aws-eks-in-production"
  validation {
    condition = (
      length(var.after_cluster_joining_userdata) < 2
    )
    error_message = "You may not specify more than one `after_cluster_joining_userdata`."
  }
}
```

## Expected Behavior
The variable to be a string or the validation to allow more than 1 element.

### PR DESCRIPTION
**Pull request by jchanam**
## what
- Allow using multiple lines of before and after userdata 

## why
- As the bash commands are added to a file, I don't see why they have to be only one line.

## references
closes #123

### CODE REVIEW

**Comment by Gowiem** [comment]
cc @Nuru since this validation was originally implemented in #84

See @jchanam's thread in Slack regarding this issue here: https://sweetops.slack.com/archives/CB6GHNLG0/p1658405157443729

**Comment by jchanam** [comment]
@Gowiem @Nuru Do you think we could move forward with this PR?

**Comment by jchanam** [comment]
@aknysh What work and testing do you need to complete the PR?

The links you've sent refer to the master status of the two lines that I've changed. I don't understand what do you need me to see there. Could you be more specific?

**Comment by Nuru** [comment]
> > > @aknysh What work and testing do you need to complete the PR?
> > > The links you've sent refer to the master status of the two lines that I've changed. I don't understand what do you need me to see there. Could you be more specific?
> > 
> > 
> > sorry, wrong message, you are correct you updated the lines
> 
> What I wanted to point out is the example needs to be updated https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/examples/complete/fixtures.us-east-2.tfvars#L35 (this is not related to your changes, the example uses a string but the var is a list of strings)

@aknysh Although it may seem a bit awkward, the example works as intended because [the variable is passed as the sole member of a list](https://github.com/cloudposse/terraform-aws-eks-node-group/blob/c611f2df9c3dcfc81790ff670a462d78bbe92364/examples/complete/main.tf#L162).

**Comment by Nuru** [comment]
@jchanam I am hesitant to approve this PR because, while it resolved the confusion you experienced, I worry that it will add confusion to someone else. Please see my comment at https://github.com/cloudposse/terraform-aws-eks-node-group/issues/123#issuecomment-1218462942 and let me know what you think.

**Comment by Nuru** [comment]
Closing this as `stale`, `wontfix`

**Pull request closed without merging**
