### PR TITLE
Initial implementation of `terraform-aws-eks-node-group`

### PR DESCRIPTION
**Pull request by aknysh**
## what
* Initial implementation of `terraform-aws-eks-node-group`
* Add `bats` and `Terratest`
* Add Codefresh test pipeline

## why
* Provision an EKS Node Group for [Elastic Container Service for Kubernetes](https://aws.amazon.com/eks/)

### CODE REVIEW

**Comment by johncblandii** [comment]
Nice. I was just looking at using a Node Group and I should've known you guys were on top of it. :)

**Comment by aknysh** [comment]
> Nice. I was just looking at using a Node Group and I should've known you guys were on top of it. :)

it's working

image

**Comment by johncblandii** [comment]
Awesome! I'm going to give it a whirl next week.

**Comment by johncblandii** [comment]
I didn't apply it (can't merge with a branch specification), but the plan definitely looks good:

```log
# module.eks_node_group_default.aws_eks_node_group.default[0] will be created
  + resource "aws_eks_node_group" "default" {
      + ami_type        = "AL2_x86_64"
      + arn             = (known after apply)
      + cluster_name    = "app-prod-cluster"
      + disk_size       = 20
      + id              = (known after apply)
      + instance_types  = [
          + "t3.medium",
        ]
      + labels          = {
          + "node_type" = "default"
        }
      + node_group_name = "app-prod-workers"
      + node_role_arn   = (known after apply)
      + release_version = (known after apply)
      + resources       = (known after apply)
      + status          = (known after apply)
      + subnet_ids      = [
          + "subnet-xxxyyyzzz",
          + "subnet-xxxyyyzzz",
          + "subnet-xxxyyyzzz",
          + "subnet-xxxyyyzzz",
        ]
      + tags            = {
          + "Attributes"                                    = "workers"
          + "Environment"                                   = "app-stack"
          + "ManagedBy"                                     = "Terraform"
          + "Name"                                          = "app-prod-workers"
          + "Namespace"                                     = "app"
          + "ReleaseStage"                                  = "PROD"
          + "Stage"                                         = "prod"
          + "kubernetes.io/cluster/app-prod-cluster" = "owned"
        }
      + version         = "1.14"

      + scaling_config {
          + desired_size = 3
          + max_size     = 10
          + min_size     = 3
        }
    }
```

**Comment by aknysh** [comment]
> I didn't apply it (can't merge with a branch specification), but the plan definitely looks good:
> 
> ```
> # module.eks_node_group_default.aws_eks_node_group.default[0] will be created
>   + resource "aws_eks_node_group" "default" {
>       + ami_type        = "AL2_x86_64"
>       + arn             = (known after apply)
>       + cluster_name    = "app-prod-cluster"
>       + disk_size       = 20
>       + id              = (known after apply)
>       + instance_types  = [
>           + "t3.medium",
>         ]
>       + labels          = {
>           + "node_type" = "default"
>         }
>       + node_group_name = "app-prod-workers"
>       + node_role_arn   = (known after apply)
>       + release_version = (known after apply)
>       + resources       = (known after apply)
>       + status          = (known after apply)
>       + subnet_ids      = [
>           + "subnet-xxxyyyzzz",
>           + "subnet-xxxyyyzzz",
>           + "subnet-xxxyyyzzz",
>           + "subnet-xxxyyyzzz",
>         ]
>       + tags            = {
>           + "Attributes"                                    = "workers"
>           + "Environment"                                   = "app-stack"
>           + "ManagedBy"                                     = "Terraform"
>           + "Name"                                          = "app-prod-workers"
>           + "Namespace"                                     = "app"
>           + "ReleaseStage"                                  = "PROD"
>           + "Stage"                                         = "prod"
>           + "kubernetes.io/cluster/app-prod-cluster" = "owned"
>         }
>       + version         = "1.14"
> 
>       + scaling_config {
>           + desired_size = 3
>           + max_size     = 10
>           + min_size     = 3
>         }
>     }
> ```

All working, Terratest passes
https://g.codefresh.io/public/accounts/cloudposse/builds/5dee9f586ebcd87c42c7c674

**Pull request merged**
