### PR TITLE
Use splat syntax to return NG underlying resources

### PR DESCRIPTION
**Pull request by maxgio92**
Hi,
this fixes for me the [issue #7](https://github.com/cloudposse/terraform-aws-eks-node-group/issues/7): 
Unfortunately I could not reproduce the issue by testing the module only.

Since this [PR #22846](https://github.com/hashicorp/terraform/pull/22846) on Terraform itself was merged, I think that the splat syntax is a better approach when looking for resources which instances  could not exist anymore, particularly during a destroy action.

Links:

- https://discuss.hashicorp.com/t/empty-tuple-error-on-modules-that-are-disabled/4544
- https://github.com/hashicorp/terraform/pull/22846

Thank you

### CODE REVIEW

**Comment by aknysh** [comment]
@maxgio92 thanks for the PR. It looks good.
could you please update the cluster version in https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/examples/complete/main.tf#L45
to the latest version `0.16.0`?
We added waiting for the cluster to be ready there, without it the test failed randomly.

thanks

**Comment by maxgio92** [comment]
> @maxgio92 thanks for the PR. It looks good.
> could you please update the cluster version in https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/examples/complete/main.tf#L45
> to the latest version `0.16.0`?
> We added waiting for the cluster to be ready there, without it the test failed randomly.
> 
> thanks

Yes, sure. Thank you

**Comment by maxgio92** [comment]
Hi @aknysh,
I updated the EKS cluster module to 0.16.0  in the main example.
Thank you

**Comment by maxgio92** [comment]
Thank you @aknysh

**Pull request merged**
